# Some code has been stolen from @enbox/enbox which I helped start lol

name: Electron/PWA CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]      
        node-version: [14.17.6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Set OS to Windows
      if: runner.os == 'Windows'
      run: echo "opsys=windows" >> $GITHUB_ENV
      # Required since default shell on Windows is pwsh
      shell: bash
    - name: Set OS to macOS (and set release flag)
      if: runner.os == 'macOS'
      run: |
        echo "opsys=macos" >> $GITHUB_ENV
    - name: Set OS to Linux
      if: runner.os == 'Linux'
      run: "opsys=linux" >> $GITHUB_ENV
    - run: rm -rf node_modules && yarn install --frozen-lockfile
    - name: Install Quasar CLI
      run: yarn global add @quasar/cli
    - run: quasar build -m electron
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: eltr-bin-${{ env.opsys }}
        path: dist\electron\io*
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn
    
